### ISSUE TITLE
Date

### ISSUE THREAD

**Issue by jmtbdj** [mr-feek/global-poker-hand-history-converter#1]
As of now the hand histories do not differentiate between AM and PM times, so the hand histories get mixed together and there is no way to tell when they were actually played. Are you able to convert them to military time (24 hour clock)?

**Comment by mr-feek** [comment]
Yeah, I need to fix [this line](https://github.com/mr-feek/global-poker-hand-history-converter/blob/master/src/GlobalPokerHand.js#L13)

thanks!

**Comment by mr-feek** [comment]
This should be fixed now & I've just released a new version of the extension @jmtbdj . Let me know if there is still an issue for you
