### ISSUE TITLE
New website design

### ISSUE THREAD

**Issue by wookie123** [mr-feek/global-poker-hand-history-converter#10]
Hi,

Are you going to update the hand history converter so we can download hands from the new web page design?

**Comment by nachishankar** [comment]
hey I'm not good at coding- but i'm going to try
Nachi

**Comment by CMaximus** [comment]
Please update!

**Comment by mr-feek** [comment]
issue is being tracked here https://github.com/mr-feek/global-poker-hand-history-converter-chrome-extension/issues/11

**Comment by wookie123** [comment]
Did a new converter get created for global poker?

    On Thursday, September 27, 2018, 10:19:03 PM EDT, nachishankar <notifications@github.com> wrote:  
 
 hey I'm not good at coding- but i'm going to try
Nachi
