### ISSUE TITLE
Site changed

### ISSUE THREAD

**Issue by rattlehead616** [mr-feek/global-poker-hand-history-converter#11]
They changed the site and I went to go export my hand histories and the converter isn't working anymore :(

**Comment by mr-feek** [comment]
https://github.com/mr-feek/global-poker-hand-history-converter-chrome-extension/issues/11

this should be fixed now, you'll need to rebuild the extension

**Comment by rattlehead616** [comment]
By "rebuild" do you mean reinstall?

**Comment by rattlehead616** [comment]
So I took another stab at figuring out how to rebuild the extension and I figured it out. Is there a limit to how many hands it can convert? I tried getting hands from mid September and it gave me an error

**Comment by rattlehead616** [comment]
Never mind I figured it out
