### ISSUE TITLE
New update broke it

### ISSUE THREAD

**Issue by Noobafied** [mr-feek/global-poker-hand-history-converter#12]
Nov 27th they updated lobby and broke it again

**Comment by mr-feek** [comment]
This is a problem with the extension, not this converter library. Tracking it here: https://github.com/mr-feek/global-poker-hand-history-converter-chrome-extension/issues/15

**Comment by Noobafied** [comment]
love you

**Comment by Noobafied** [comment]
literally begging you to message me on discord Noobafied#5462
