### ISSUE TITLE
Update for Global converter

### ISSUE THREAD

**Issue by wookie123** [mr-feek/global-poker-hand-history-converter#13]
It looks like global has update their site.  Are there any plans to update the hand history converter?  I would be willing to send some money via paypal if so.

**Comment by mr-feek** [comment]
@wookie123 I updated the extension a few days ago with the fix: https://github.com/mr-feek/global-poker-hand-history-converter-chrome-extension

you'll need to rebuild it

**Comment by wookie123** [comment]
So I got banned from Global a while back for having this installed and downloading hands.  Is there a way to use it so that Global will not know?  Like if I install it in the browser once per month, download all my hands, then uninstall it.  Will Global find out?
Thank you
    On Friday, November 30, 2018, 2:57:07 PM PST, Fiachra McDermott <notifications@github.com> wrote:  
 
 
Closed #13.

**Comment by mr-feek** [comment]
I no longer support this chrome extension due to how many bans were put in place. Use at your own discretion
