### ISSUE TITLE
Invalid Pot Size

### ISSUE THREAD

**Issue by jmtbdj** [mr-feek/global-poker-hand-history-converter#2]
Getting this error often when importing to PT4 - seems to be around 5 of every 1000 hands. I don't notice anything different when the error occurs compared to when it doesn't. Here is a sample hand history where the error occurs:

PokerStars Game #1516251700049:  Hold'em No Limit ($0.25/$0.5 USD) - 2018/01/18 12:1:40 ET
Table 'High Point 40-100 bb' 6-max Seat #4 is the button
Seat 1: Player#7895 ($37.75 in chips)
Seat 2: Player#3159 ($50 in chips)
Seat 3: Player#6392 ($50 in chips)
Seat 4: Player#0654 ($80.86 in chips)
Seat 5: Player#5552 ($68.6 in chips)
Seat 6: Hero ($80.73 in chips)
Player#5552: posts small blind $0.25
Hero: posts big blind $0.5
*** HOLE CARDS ***
Dealt to Hero [9s 4s]
Player#7895: folds
Player#3159: folds
Player#6392: calls $0.5
Player#0654: calls $0.5
Player#5552: calls $0.25
Hero: checks
*** FLOP *** [Kc 4c 3h]
Player#5552: checks
Hero: checks
Player#6392: checks
Player#0654: checks
*** TURN *** [Kc 4c 3h] [8s]
Player#5552: checks
Hero: checks
Player#6392: checks
Player#0654: bets $1.12
Player#5552: calls $1.12
Hero: folds
Player#6392: folds
*** RIVER *** [Kc 4c 3h] [8s] [Jd]
Player#5552: checks
Player#0654: checks
*** SHOW DOWN ***
Player#5552: shows [2s 3s] (a pair)
Player#0654: shows [Ad 8h] (a pair)
*** SUMMARY ***
Total pot $4.49 | Rake $0.22
Board [Kc 4c 3h 8s Jd]
Seat 4: Player#0654 showed [Ad 8h] and won ($4.27) with a pair
Seat 2: Player#3159 folded
Seat 5: Player#5552 showed [2s 3s] and lost with a pair
Seat 3: Player#6392 folded
Seat 1: Player#7895 folded
Seat 6: Hero folded

**Comment by mr-feek** [comment]
I've noticed this a few times too, I'll have a closer look this weekend. Thanks

**Comment by mr-feek** [comment]
@jmtbdj 
This should be fixed now in extension version `0.2.2`. Let me know if there are still any hands that fail!

**Comment by mr-feek** [comment]
PS I highly recommend you purge your existing imported hands, and re-import. There were a few bugs determining posted dead blinds and side pots.
