### ISSUE TITLE
Omaha HH's?

### ISSUE THREAD

**Issue by guy111** [mr-feek/global-poker-hand-history-converter#3]
Will this also support Omaha?

**Comment by mr-feek** [comment]
Hey @guy111 , I don't really play omaha so I don't have any plans to personally implement the omaha hand conversions.

I'm happy to merge any code if someone else is able to implement it though!

**Comment by mr-feek** [comment]
Support has now been added in with this [PR](https://github.com/mr-feek/global-poker-hand-history-converter/pull/7)  . Thanks to @romankor !

**Comment by mr-feek** [comment]
Just published `Version: 0.3.0` of the chrome extension. Should be available to everyone within the hour.

**Comment by wookie123** [comment]
Will you consider adding support for hand 2 note?  I uploaded some of the hand histories into this program and noticed that they are not uploading correctly.

**Comment by mr-feek** [comment]
@wookie123 I don't have `hand 2 note`, so I'm not really interested in spending time figuring out what it needs done to work properly. Maybe you can open a new issue asking for support for that, and someone else who uses it might be interested in making it work.
