### ISSUE TITLE
Global Poker Lobby Redesign Issue

### ISSUE THREAD

**Issue by chrisp200** [mr-feek/global-poker-hand-history-converter#9]
Since Global Poker updated their lobby, the hand history download button doesn't appear anymore.

Is this just a CSS issue?  Is it looking for a class that isn't there anymore?

**Comment by mr-feek** [comment]
Gonna close this issue, the chrome extension issue can be tracked here: https://github.com/mr-feek/global-poker-hand-history-converter-chrome-extension/issues/11
